const cities = [
{lineId: 1, number: 1, link: "http://demdikk.com/ligne-1-parcelles-assainies-place-leclerc/",destination:["Terminus des Parcelles","Corniche (unités 10-9-15)","Dior","Acapes Dispensaire Norade","Passage entre 22 et 24","Virage à droite","Tronçon Marché Grand-Médine","VDN","Relais","Avenue Cheikh Anta Diop","Avenue Blaise Diagne","Avenue Jean Jaurès","Avenue André Peytavin","Avenue George Pompidou","Place de l’Indépendance","allées Canard","Esso Port","Embarcadère","Place Leclerc"],},
{lineId: 2,number: 2, link: "http://demdikk.com/ligne-2-daroukhane-p-leclerc/", destination:["Daroukhane","Corniche-Hamo","Terminus Guédiawaye","Marché Sahm","Ecole Canada","Route des Niayes","Tally Boumack(route de l’Ouest)","Route Nationale n° 1","Autoroute","Cité des Eaux","Avenue Bourguiba","Avenue Cheikh Ahmadou Bamba (ex Rue 13 Prolongée)","Bld Général De Gaule","Rue 25","Avenue Blaise Diagne","Avenue Jean Jaurès","Avenue Georges Pompidou","Place de l’Indépendance","Esso Port","Leclerc"]},
{lineId: 3, number: 4, link: "http://demdikk.com/ligne-4-liberte-5-p-leclerc/",destination: ["Terminus Dieuppeul","Cité Derklé","Khar Yalla","Cité Marine","CEG Dieuppeul 3","Camp Sapeurs Pompiers","Cité Sacré Cœur","Collège Sacré Cœur","Sicap Karack","Avenue Bourguiba","Dial Diop ex rue 10","Point E","HLM Fass","Canal Gueule Tapée","Avenue Blaise Diagne","Avenue Jean Jaurès","Boulevard de la République","Avenue Léopold Sédar Senghor","Allées Canard-Esso"]},
{lineId: 4, number: 5, link: "http://demdikk.com/ligne-5-guediawaye-palais-1/",destination: ["Terminus Guédiawaye","Route de la Corniche","Cité des Enseignants","Maison du PAI","Cité Hlm","Golf","Route des Niayes","Police des Parcelles Assainies","Pont du Stade Léopold Sédar Senghor (Echangeur)","Patte d’Oie","Autoroute","Passage Cyrnos","Avenue Lamine Guèye","Avenue André Peytavin","avenue Jean Jaurès","Bld de la République","Avenue Léopold Sédar Senghor","Avenue Nelson Mandela","Palais de Justice"]},
{lineId: 5, number: 6, link: "http://demdikk.com/ligne-6-camberene-2-palais-2/", destination: ["Cambéréne 2","Cambéréne village","Case","Route des Niayes","Police des Parcelles Assainies","Marché Grand-Médine","Cité Keur Damel","VDN Sipres","Camp Pénal","Derklé","Liberté 5","Allées Khalifa Ababacar Sy","Jet d’Eau","Niary Tally","Enam","Bld Général De Gaule","Allées Papa Guèye Fall","Avenue Faidherbe","Avenue Lamine Guèye","Avenue André Peytavin","Avenue Jean Jaurès","Bld de la République","Avenue Nelson Mandela","Palais 2"]},
{lineId: 6, number: 7, link: "http://demdikk.com/ligne-7-ouakam-palais-2/", destination:["Terminus Ouakam","Cité Assemblée","Comico","Av Cheikh Anta Diop (route de Ouakam)","Avenue Blaise Diagne","avenue Jean Jaurès","Avenue André Peytavin","Avenue Georges Pompidou","Place de l’Indépendance","Avenue Léopold Sédar Senghor","Avenue Nelson Mandela","Palais de Justice"]},
{lineId: 7, number: 8, link: "http://demdikk.com/ligne-8-aeroport-yoff-palais-2/", destination: ["Terminus Aéroport","Cité Asecna","Yoff Village","Stade Léopold Sédar Senghor","Patte d’Oie","Grand Yoff","Cité des Eaux","Avenue Bourguiba","Rue Dial Diop(ex rue 10)","Zone B","Rocade Fann","Bel Air (Point E)","Avenue Cheikh Anta Diop (Cité Universitaire)","Avenue Blaise Diagne","Avenue Jean Jaurès","Bld de la République","Avenue Léopold Sédar Senghor","Avenue Nelson Mandela","Palais de Justice"]},
{lineId: 8, number: 9, link: "http://demdikk.com/ligne-9-liberte-6-palais-2/", destination:[ "Liberté 6","Sacré Cœur","Terminus Dieuppeul","Allées Ababacar Sy","Rond Point Jet d’Eau","Allées Cheikh Sidate (Niary Tally)","Eglise Sainte Thérèse","Avenue Dial Diop (ex rue 10)","Bld Général De Gaule","Avenue Malick Sy","Avenue Blaise Diagne","Avenue Jean Jaurès","Avenue André Peytavin","Avenue Pompidou","Avenue Léopold Sédar Senghor","Avenue Nelson Mandela","Palais 2"]},
{lineId: 9, number: 10, link: "http://demdikk.com/ligne-10-liberte-5-palais-2/", destination: ["Terminus Dieuppeul","Cité Derklé","Khar Yalla","Cité Marine","CEG Dieuppeul 3","Eglise Martyrs de l’Ouganda (rue 11 x P)","Stade Marius Ndiaye  Avenue Bourguiba","Relais","Avenue Cheikh Anta Diop","Rue Aimé Césaire","Corniche Ouest","Village Artisanal de Soubédioun","Prison Central","Bld de la République","Avenue Léopold Sédar Senghor","Avenue Nelson Mandela","Palais 2"]},
{lineId: 10, number: 11, link: "http://demdikk.com/ligne-11-keur-massar-lat-dior/", destination: ["Terminus Keur Massar","Parcelles Assainies (keur Massar) Route de Boune","Fass Mbao","Diamaguène","Thiaroye/mer","Croisement Pikine","Route Nationale","Autoroute","Corniche des Hlm","Colobane","Caisse de sécurité sociale","Bd Général De Gaule (Centenaire)","RTS","Rond Point Poste Médina","Blaise Diagne","Sandaga","Terminus Lat-Dior"]},
{lineId: 11, number: 12, link: "http://demdikk.com/ligne-12-guediawaye-palais-1/", destination: ["Terminus Guédiawaye","Cité des Enseignants","Maison du PAI","Hlm Guédiawaye","Domaine de Guédiawaye","Lycée Canada","Route des Niayes","Tally Boubess","Marché poissons","Route de Rufisque","Capa","TP Cap Vert","Cité des Eaux","Avenue Bourguiba","Relais Avenue Cheikh Anta Diop  (Hôpital Fann)","Avenue Blaise Diagne","Avenue Jean Jaurès","Bld de la République","Avenue Léopold Sédar Senghor","Avenue Nelson Mandela","Palais de Justice"]},
{lineId: 12, number: 13, link: "http://demdikk.com/ligne-13-liberte-5-palais-2/", destination: ["Terminus Dieuppeul","Avenue Cheikh Ahmadou Bamba (ex rue 13 Prolongée)","Station Castors","Cité Port","Lycée Kennedy","Bld Général De Gaule","Allées Papa Guèye Fall","Avenue Faidherbe","Esso Port","Place de l’Indépendance","Avenue Léopold Sédar Senghor","Avenue Nelson Mandela","Palais 2"]},
{lineId: 13, number: 15, link: "http://demdikk.com/ligne-15-rufisque-palais-1/", destination: ["Terminus Rufisque","Mosquée Keuri Kaw","Sortie Rufisque (Dioukoul)","Sicap Mbao","Diamaguène","Croisement Pikine","Route de Rufisque","SCOA","SONACOS","Bld de l’Arsenal","Esso Port","Place de l’Indépendance","Avenue Léopold Sédar Senghor","Avenue Nelson Mandela","Palais 1"]},
{lineId: 14, number: 18, link: "http://demdikk.com/ligne-18-dieuppeul-dieuppeul/", destination: ["Terminus Dieuppeul","Cité Derklé","Khar Yalla","Cité Marine","Avenue Cheikh Ahmadou Bamba (ex rue 13 Prolongée)","Station Castors","Cité Port","Rocade Fann Bel Air","Colobane","Police Bel Air","Grand Moulin de Dakar","Quai de pêche","Esso Port","Place de l’Indépendance","Avenue Georges Pompidou","Avenue André Peytavin","Route de la Corniche","Avenue Malick Sy","Rue 6","Gueule Tapée","Lycée Delafosse","Avenue Cheikh Anta Diop","Ecole Normale Supérieure","Avenue Bourguiba","Rond Point Jet d’eau","Allées Ababacar Sy","Terminus Dieuppeul"]},
{lineId: 15, number: 20, link: "http://demdikk.com/ligne-20-dieuppeul-dieuppeul/", destination: ["Terminus Dieuppeul","Allées Ababacar Sy","Jet d’eau","Avenue Bourguiba","Ecole Police(Relais)","Avenue Cheikh Anta Diop","Hôpital Fann","Cité Universitaire","Lycée Delafosse","HLM Gueule Tapée","Rue 6","Avenue  Malick Sy","Corniche Ouest","Avenue Peytavin","Avenue Pompidou","Place de l’Indépendance Esso Port","Bld de l’Arsenal","Central Bel Air (MTOA)","Grands Moulin de Dakar","Police Bel Air","Colobane","Angle Mousse","Avenue Cheikh Ahmadou Bamba","Station Castors","Cité Marine Khar Yalla","Cité Derklé","Terminus Dieuppeul"]},
{lineId: 16, number: 23, link: "http://demdikk.com/ligne-23-parcelles-assainies-palais-1/", destination: ["Terminus des Parcelles","Ecole Dior","Cités Diamalaye","Hlm Grand Médine","Reprise Route du Terminus","Eglise","Route des Niayes","Echangeur du Stade Léopold Sédar Senghor (Amitié)","Cité Keur Khadim","Camp Pénal","Route du Front de Terre","Cité des Eaux","Avenue Bourguiba","Relais","Avenue Cheikh Anta Diop (Route de Ouakam)","Marché SAHM","Gueule Tapée","Rue 6","Avenue Malick Sy","Avenue Blaise Diagne","Avenue Jean Jaurès","Bld de la République","Avenue Léopold Sédar Senghor","Hôpital Principal","Avenue Nelson Mandela","Hôpital Le Dantec","Palais de Justice"]},

 {lineId: 17, number: 121, link: "http://demdikk.com/ligne-121-scat-urban-leclerc/", destination: ["Terminus Scat Urban","Mairie grand Yoff","Cité Cse","Les deux voies de Sipres","Les deux voies de Liberté 6","Collège Sacré Cœur","Sicap rue 10","Lycée Blaise Diagne","Place ONU","Canal 4","HLM Fass","Travaux communaux","rue 22 prolongée","RTS","Allées Papa Guèye Fall","Avenue Faidherbe","Place de l’indépendance","Albert Sarraut","Terminus Leclerc"]}
];
export default cities;
